"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const UserController_1 = __importDefault(require("./controllers/UserController"));
const MentorController_1 = __importDefault(require("./controllers/MentorController"));
const TeamController_1 = __importDefault(require("./controllers/TeamController"));
const MentoringController_1 = __importDefault(require("./controllers/MentoringController"));
const routes = express_1.Router();
routes.get('/users', UserController_1.default.index);
routes.post('/users', UserController_1.default.store);
routes.put('/users/:id', UserController_1.default.update);
routes.delete('/users/:id', UserController_1.default.delete);
routes.get('/mentors', MentorController_1.default.index);
routes.post('/mentors', MentorController_1.default.store);
routes.put('/mentors/:id', MentorController_1.default.update);
routes.delete('/mentors/:id', MentorController_1.default.delete);
routes.get('/teams', TeamController_1.default.index);
routes.post('/teams', TeamController_1.default.store);
routes.put('/teams/:id', TeamController_1.default.update);
routes.get('/mentorings', MentoringController_1.default.index);
routes.post('/mentorings', MentoringController_1.default.store);
routes.put('/mentorings/:id', MentoringController_1.default.update);
exports.default = routes;
